import { IIcon } from "./types";

export const defaultColor = "#000000"
export const availabelColors = ["#f44336", "#e91e63", "#9c27b0", "#673ab7", "#a4a9c8", "#2196f3", "#29a9e1", "#00bcd4", "#009688", "#4caf50", "#8bc34a", "#cddc39", "#ffeb3b", "#ffc107", "#ff9800", "#ff5722", "#795548", "#607d8b", "#000000"];

export const AddIcon: IIcon = {
    id: "1",
    source: "local",
    path: "add.svg",
    name: "add",
    width: 15,
    height: 15,
    size: 1,
    color: defaultColor,
};

let icon_id = 0;

export const startIcon: IIcon = { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Start.svg', name: 'Love', size: 1, color: defaultColor };
export const endIcon: IIcon = { id: (icon_id++).toString(), width: 45, height: 15, source: "local", path: 'pictosso/End.svg', name: 'Love', size: 1, color: defaultColor };
export const signature: IIcon = { id: (icon_id++).toString(), width: 50 * 2, height: 12 * 2, source: "local", path: 'pictosso/signature.svg', name: 'Signature', size: 1, color: defaultColor };

export const icons: IIcon[] = [

    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Love.svg', name: 'Love & Life', size: 1, color: defaultColor, description: 'This heart icon is a vivid emblem of Love & Life. It signifies the heartbeat of life itself, the pulse that drives us forward through each day. It represents the timeless dance of love that weaves through the fabric of our lives, filling our days with joy, warmth, and connection. This icon is a tribute to the intertwined beauty of living and loving, a reminder that our lives are enriched by the love we give and receive.', usage: "Use this icon to celebrate moments of love and joy, such as anniversaries, romantic milestones, or times when life’s beauty and vibrancy were most deeply felt." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Adventure.svg', name: 'Adventure', size: 1, color: defaultColor, description: "This icon, featuring a compass encircling the globe, captures the essence of adventure. The compass symbolizes the pursuit of new directions and uncharted paths, while the globe represents the vast, unexplored world waiting to be discovered. This icon celebrates the thrill of adventure, the excitement of stepping into the unknown, and the joy of discovering new horizons. It embodies the spirit of exploration, the courage to seek out new experiences, and the transformative power of adventure.", usage: "Use this icon to mark daring journeys and adventurous undertakings, such as embarking on a bold expedition, exploring wild landscapes, or starting an exciting new quest. It symbolizes the adventurous spirit and the boundless possibilities that come with every daring endeavor." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Birth.svg', name: 'Birth', size: 1, color: defaultColor, description: "This icon is a poetic depiction of birth, capturing the essence of life's miraculous beginning. The circle represents the purity and completeness of a newborn, while the semicircle evokes the protective embrace of a parent. The abstract form symbolizes the delicate emergence of new life, a tiny being cradled in the embrace of the universe. The curves and shapes evoke the tenderness and protection surrounding this fragile moment, highlighting the purity, hope, and boundless potential that each new life brings. This icon celebrates the wonder of birth, a timeless reminder of the beauty and continuity of life itself.", usage: "Use this icon to mark the arrival of a new life, celebrating births, and welcoming the newest additions to your family.", },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Car.svg', name: 'Car', size: 1, color: defaultColor, description: "This icon, with its five bold bolts, captures the essence of a car. The circular arrangement evokes the image of a wheel, and each bolt, integral to the wheel's structure, represents the mechanics and precision that drive the car forward. This abstract design celebrates the spirit of adventure and exploration, the freedom of the open road. It embodies the intricate mechanics that make travel possible and the endless possibilities that lie in every journey. This icon is a tribute to the harmony of form and function, a symbol of the seamless blend of engineering and the thrill of the ride.", usage: "Use this icon to commemorate milestones such as buying a new car, embarking on memorable road trips, or celebrating journeys of exploration and adventure." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Financial milestone.svg', name: 'Financial milestone', size: 1, color: defaultColor, description: "This icon, depicting one coin growing into a larger one, beautifully captures the essence of financial success and growth. The transformation symbolizes the journey from modest beginnings to significant achievements, reflecting investments and prosperous trades. This icon celebrates the rewards of hard work and the fulfillment of financial goals. It embodies the promise of abundance, the excitement of wealth accumulation, and the satisfaction of reaching new financial heights.", usage: "Use this icon to mark financial milestones such as reaching savings goals, making successful investments, achieving financial independence, or celebrating career promotions that bring financial growth." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Graduation.svg', name: 'Studies & Graduation', size: 1, color: defaultColor, description: "This icon, designed to represent a book, captures the essence of graduation and the journey of education. The open book symbolizes the knowledge gained through years of study, each page a testament to lessons learned. The line running through the middle represents the path forward, guiding graduates into the professional world and future opportunities. This icon celebrates academic achievements and the transition from student to professional. It embodies dedication, hard work, and the promising doors that education opens.", usage: "Use this icon to mark milestones such as graduation ceremonies, completing a degree, achieving academic honors, or starting new educational pursuits. It symbolizes the journey of learning and the exciting future ahead." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Holidays.svg', name: 'Holidays', size: 1, color: defaultColor, description: "This icon, with its evocative design, beautifully captures the essence of holidays. It can be seen as a sunset over the sea, where the half-sun dips below the horizon, casting its warm glow on the tranquil waters. Alternatively, it might represent a palm tree, a quintessential symbol of tropical getaways. Some might even see a cozy lamp inviting you to relax with a good book. Whatever interpretation resonates with you, this icon embodies the warmth and serenity of a perfect holiday. It is a symbol of relaxation, escape, and the joy of finding yourself in a beautiful, restful place. The shape evokes feelings of peace and contentment, transporting you to your dream holiday destination.", usage: "Use this icon to mark your cherished holiday moments, such as memorable vacations, serene getaways, or special trips that offered a break from the everyday routine. It symbolizes the joy of relaxation and the beauty of new, refreshing experiences." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Home.svg', name: 'New Home', size: 1, color: defaultColor, description: `This icon beautifully captures the essence of "Home." The design features a roof, symbolizing the cozy shelter a home provides. Beneath it, the door welcomes you to a space filled with warmth and love, with a path leading to this inviting place, symbolizing the journey towards comfort and happiness. The entire design radiates a sense of welcome, offering a haven of warmth and care. It is a place where life’s most treasured moments unfold, where laughter and love abound, and where memories are made. This icon is a poetic tribute to the idea of home as a source of joy and belonging. It celebrates the delightful feeling of finding a place that offers love, new beginnings, and a foundation for countless cherished moments.`, usage: "Use this icon to mark significant milestones such as moving to a new place, buying a home or apartment, or creating a new space filled with love and happiness. It represents the joy of new beginnings and the comfort of finding your place in the world." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Kiss.svg', name: 'First Kiss', size: 1, color: defaultColor, description: "This icon is an abstract representation of two people sharing their first kiss, a tender moment of connection and embrace. The two triangles symbolize the faces of the lovers, drawn together in a moment of profound intimacy. The V-shape at the center represents their embracing arms, encircling each other in a delicate dance of affection. It captures the profound simplicity of this intimate act, where two souls meet and intertwine, creating a spark that transcends words. The gentle curves and lines evoke the warmth of closeness and the beauty of vulnerability. This icon immortalizes the magic of the first kiss, a milestone in the journey of love, marking the beginning of a shared story filled with passion and intimacy.", usage: "Use this icon to commemorate the memory of your first kiss, capturing the magic and intimacy of that unforgettable moment in your love story." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Meeting someone.svg', name: 'Meeting someone', size: 1, color: defaultColor, description: "This icon captures the profound moment of encountering a life-changing individual. The two shapes represent two people connecting, their paths intertwining in a meaningful way. Resembling comets colliding, these forms evoke the explosive impact such a meeting can have, symbolizing the significant influence one person can bring to your life's journey. The imagery of comets colliding speaks to the intensity and brilliance of such an encounter. When two lives intersect in this manner, it often leads to a burst of new possibilities, ideas, and emotions, much like the spectacular explosion that occurs when celestial bodies meet. This icon encapsulates the essence of these transformative connections, celebrating their power to alter the trajectory of our lives.", usage: "Use this icon to mark those pivotal moments when a new connection altered the course of your life. Whether it’s meeting a mentor who guided you, a lifelong friend who stood by you, or a romantic partner who became your soulmate, this icon honors the transformative power of human connection and the remarkable changes it can inspire." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Music event.svg', name: 'Musical', size: 1, color: defaultColor, description: "This icon, with its flowing design, beautifully captures the essence of music. The elegant waves symbolize the captivating waves of sound that music creates, filling the air with rhythm and melody. It can also be seen as a concert, with a soul at the center surrounded by the harmonious waves of music. This icon celebrates the power of music to move us, to create emotions, and to bring people together. It embodies the joy, passion, and connection that music brings into our lives, transforming moments into memories through its enchanting presence.", usage: "Use this icon to mark significant musical moments, such as attending a concert, discovering a favorite song, or celebrating a musical achievement. It symbolizes the beauty of music and its ability to resonate deeply within us, making life more vibrant and expressive." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/New business.svg', name: 'New business', size: 1, color: defaultColor, description: "This icon, elegantly designed as a ship poised to take off, captures the spirit of embarking on new ventures and reaching for dreams. The two triangles at the base symbolize powerful boosters, representing the strong foundation and support required to achieve your goals. As the ship ascends, it embodies ambition, determination, and the limitless possibilities of the future. In its abstract form, this icon celebrates the excitement and potential of new beginnings. It is a tribute to the bold steps taken towards innovation and success, the courage to explore uncharted territories, and the drive to turn visions into reality. This icon is a beacon of hope and aspiration, guiding you towards the fulfillment of your dreams.", usage: "Use this icon to commemorate the start of a new business, the launch of a creative project, or any milestone marking the pursuit of your goals and ambitions. It symbolizes the journey of entrepreneurship, the leap of faith into new opportunities, and the unwavering belief in the power of your dreams." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/New job.svg', name: 'Promotion & New Job', size: 1, color: defaultColor, description: "This icon, with its three ascending steps, poetically captures the journey of career growth and advancement. Each step represents a significant milestone: where we were, the new position we've been promoted to, and the next goal we are striving for. It embodies the continuous pursuit of professional excellence and the ambition to reach ever higher. This icon celebrates the achievements of new jobs and promotions. It symbolizes the hard work, dedication, and aspirations that drive us forward in our careers. Each step is a testament to our progress, reflecting the journey of personal and professional development.", usage: "Use this icon to mark career milestones such as starting a new job, receiving a promotion, or setting new professional goals. It stands for the relentless pursuit of growth and the excitement of new opportunities." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Personal achievement.svg', name: 'Personal achievement', size: 1, color: defaultColor, description: "This icon, with its striking design, beautifully captures the essence of personal achievement. The mountain symbolizes the effort and challenges faced on the journey to success, representing the strength and perseverance required to reach the summit. The rounded shape behind the mountain signifies the rising sun, symbolizing the final achievement and the beauty of that hard-earned success. This icon celebrates the triumph of personal goals, the resilience to overcome obstacles, and the joy of realizing one's dreams. It embodies the dedication, determination, and fulfillment that come with reaching new heights in life.", usage: "Use this icon to mark significant personal milestones, such as achieving a long-term goal, overcoming a major challenge, or celebrating a personal victory. It symbolizes the spirit of perseverance and the radiant joy that comes with personal accomplishment." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Pet.svg', name: 'Pet', size: 1, color: defaultColor, description: "This delightful icon, featuring a triangular nose and two ears, is a poetic tribute to our beloved pets. The triangular ears, perked up in curiosity, symbolize their attentive and loyal nature. The nose, also triangular, captures their playful and affectionate spirit. This icon celebrates the bond between humans and pets, marked by trust, companionship, and shared joy. It embodies the warmth and comfort that pets bring into our lives, reminding us of the pure, unspoken love that brightens our days.", usage: "Use this icon to celebrate the arrival of a new pet, honor the memory of a beloved companion, or mark special moments shared with your furry friends." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Retirement.svg', name: 'Retirement', size: 1, color: defaultColor, description: "This icon, beautifully designed to represent a bird, captures the essence of retirement with poetic grace. The bird symbolizes the freedom and beauty that come with retirement, embodying the joy of soaring high, unburdened by the constraints of a structured life. This freedom is a celebration of years of hard work, now giving way to endless possibilities and new adventures. Just as birds inspire us with their graceful flight, a wise retiree can inspire younger generations with their experiences and wisdom. This icon is a tribute to the inspiring journey of retirement, reflecting the serene freedom and the legacy of knowledge that retirees impart.", usage: "Use this icon to commemorate the milestone of retirement, celebrating the transition into a life filled with freedom, exploration, and the sharing of wisdom. It symbolizes the joyous new chapter of life that awaits, filled with opportunities to soar high and inspire others." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Significant event.svg', name: 'Significant event', size: 1, color: defaultColor, description: "This icon, with its dynamic design, captures the essence of significant, unexpected events. Resembling an asterisk, it symbolizes the importance and multiple facets of these moments. Simultaneously, its resemblance to a storm or flash evokes the sudden and surprising nature of such events, arriving swiftly and leaving a lasting impact. This icon celebrates the remarkable and unforeseen milestones that shape our lives. It embodies the unpredictability and intensity of significant events, reminding us of the moments that come without warning but leave a profound imprint on our journey.", usage: "Use this icon to mark pivotal moments such as unexpected opportunities, surprise achievements, or any other significant life events. It symbolizes the dual nature of these experiences—both their sudden arrival and their enduring significance." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Spiritual event.svg', name: 'Spiritual event', size: 1, color: defaultColor, description: "This icon, with its serene design, encapsulates the essence of spiritual moments. The base shape represents two hands joined in prayer, a universal gesture of reverence and devotion. Above, the semi-circle symbolizes the divine, the highness of a god, or the spiritual realm we reach out to in times of reflection. This icon celebrates transformative spiritual experiences, embodying the union of human and divine. It speaks to the tranquility and grace of these moments, highlighting the peace and enlightenment they bring.", usage: "Use this icon to mark significant spiritual milestones, such as prayer, meditation, religious ceremonies, or personal revelations. It symbolizes the deep connection between the earthly and the divine, reminding us of the sacred moments that uplift our souls." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Sport event.svg', name: 'Sport event', size: 1, color: defaultColor, description: "This icon, with its powerful design, encapsulates the essence of sport achievement. It represents a head at the center and two arms raised in victory, symbolizing the triumphant moment of a winner. The overall form also represents a target, embodying the intense focus and determination required to reach sporting goals. This icon celebrates the spirit of athletic accomplishment, the relentless pursuit of excellence, and the joy of achieving one's aspirations. It embodies the dedication, hard work, and perseverance that drive athletes to surpass their limits and hit their targets.", usage: "Use this icon to mark significant sports milestones, such as winning a competition, achieving a personal best, or reaching a fitness goal. It symbolizes the victorious spirit and the unwavering focus that define sports achievements, capturing the essence of triumph and dedication." },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'pictosso/Wedding.svg', name: 'Wedding', size: 1, color: defaultColor, description: "This icon, elegantly shaped like a diamond, poetically captures the essence of a wedding. The diamond's form symbolizes not only the timeless beauty and enduring strength of the bond being formed but also the unification of two souls into one. The intersecting lines at the center represent the coming together of two individuals, merging their lives, hearts, and dreams into a single, radiant union. Just as a diamond is forged under pressure to become something extraordinary, this icon signifies the precious and unbreakable nature of the commitment made on this special day. It is a testament to love's transformative power and the dazzling brilliance of two lives entwined as one.", usage: "Use this icon to commemorate weddings and unions, marking the day two hearts became one and began their journey together." },
]

export const iconsByKey: { [key: string]: IIcon } = icons.reduce((acc, curr) => ({ ...acc, [curr.name]: curr }), {});

export const iconLetters: IIcon[] = [
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/a.svg', name: 'A', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/b.svg', name: 'b', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/c.svg', name: 'c', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/d.svg', name: 'd', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/e.svg', name: 'e', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/f.svg', name: 'f', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/g.svg', name: 'g', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/h.svg', name: 'h', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/i.svg', name: 'i', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/j.svg', name: 'j', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/k.svg', name: 'k', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/l.svg', name: 'l', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/m.svg', name: 'm', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/n.svg', name: 'n', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/o.svg', name: 'o', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/p.svg', name: 'p', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/q.svg', name: 'q', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/r.svg', name: 'r', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/s.svg', name: 's', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/t.svg', name: 't', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/u.svg', name: 'u', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/v.svg', name: 'v', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/w.svg', name: 'w', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/x.svg', name: 'x', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/y.svg', name: 'y', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'letters/z.svg', name: 'z', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/0.svg', name: '0', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/1.svg', name: '1', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/2.svg', name: '2', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/3.svg', name: '3', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/4.svg', name: '4', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/5.svg', name: '5', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/6.svg', name: '6', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/7.svg', name: '7', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/8.svg', name: '8', size: 1, color: defaultColor },
    { id: (icon_id++).toString(), width: 15, height: 15, source: "local", path: 'numbers/9.svg', name: '9', size: 1, color: defaultColor },
]